-- orders
INSERT INTO ORDERS (ID, CUSTOMER_ID, TOTAL_PRICE) VALUES (1, 1, 55.0);
INSERT INTO ORDERS (ID, CUSTOMER_ID, TOTAL_PRICE) VALUES (2, 2, 28.0);
INSERT INTO ORDERS (ID, CUSTOMER_ID, TOTAL_PRICE) VALUES (3, 3, 60.0);

-- join for list of CDs inside an order
INSERT INTO ORDER_LIST_OF_CDS (ORDERS_ID, LIST_OF_CDS) VALUES (1, 1);
INSERT INTO ORDER_LIST_OF_CDS (ORDERS_ID, LIST_OF_CDS) VALUES (1, 2);

INSERT INTO ORDER_LIST_OF_CDS (ORDERS_ID, LIST_OF_CDS) VALUES (2, 3);

INSERT INTO ORDER_LIST_OF_CDS (ORDERS_ID, LIST_OF_CDS) VALUES (3, 2);
INSERT INTO ORDER_LIST_OF_CDS (ORDERS_ID, LIST_OF_CDS) VALUES (3, 4);
