INSERT INTO PERSONS (ID, NAME, CASHBACK_TOTAL) VALUES (1, 'Romero', 0.0);
INSERT INTO PERSONS (ID, NAME, CASHBACK_TOTAL) VALUES (2, 'Bruno', 0.0);
INSERT INTO PERSONS (ID, NAME, CASHBACK_TOTAL) VALUES (3, 'Castor', 0.0);